---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - keington.github.com
  resources:
  - redissentinels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keington.github.com
  resources:
  - redissentinels/finalizers
  verbs:
  - update
- apiGroups:
  - keington.github.com
  resources:
  - redissentinels/status
  verbs:
  - get
  - patch
  - update
